In [46]:
import pandas as pd
import numpy as np
import io

In [47]:
# ==== File Paths ====
duelist_file = r"Input_Files/duelist 28.02.2026.xlsx"
duelist_main_file = r"Input_Files/Duelist 26th Feb, 2026.xlsb"
output_file = r"Output_Files/updated_duelist.xlsx"

duelist = pd.read_excel(
    duelist_file,
    dtype={"MainCode": str, "AcCodeForChg": str},
    engine="openpyxl"
)

if duelist_main_file.endswith(".xlsb"):
    duelist_main = pd.read_excel(duelist_main_file, 
                                 dtype={"MainCode": str, "AcCodeForChg": str, "Nominee": str},
                                 engine="pyxlsb")
else:
    duelist_main = pd.read_excel(duelist_main_file, 
                                 dtype={"MainCode": str, "AcCodeForChg": str, "Nominee": str},
                                 engine="openpyxl")

duelist = duelist[(duelist['ClientCode']!="~~~~~")]
print(len(duelist))
duelist.head(2)

27454

,BBB,AT,AcTypeDesc,CC,OldClientCode,ClientCode,OldAcNum,MainCode,Name,Address,...,ModelDetails,LotNumber,DownPayment,VehicleModel,VehicleNo,Region,Obligor,DistrictCode,IntRateOfChgAc,ExpiryDateOfChgAc
0,001,20,HP-3WH (TEMPO),01,NaN,00024235,NaN,00102000024235000002,BISHONATH MAHATO,SAKHUWA PRASAUNI SAKHUWA PRASAUNI PARSA,...,FOTON OMEGA STREAM,NaN,40% Downpayment,5 FOTON,NaN,NaN,NaN,025,17.0,17/01/2026
2,001,21,HP-2WH NEPAL ARMY SCHEME,01,NaN,00010670,NaN,00102100010670000006,SAIRA SHAKYA,GUITOLE LALITPUR,...,Ray ZR Disc Hybrid 125 Street Rally OBII,NaN,30% Downpayment,2 SCOOTER,NaN,CENTRAL,NaN,029,15.0,21/07/2025

In [48]:
def clean_columns(df):
    df.columns = df.columns.str.strip()
    return df

duelsit = clean_columns(duelist)
duelist_main = clean_columns(duelist_main)

In [49]:
duelist['AgeingDays'] = pd.to_numeric(duelist['AgeingDays'], errors='coerce')
duelist = duelist.sort_values(by='AgeingDays', ascending=False)
duelist['AgeingDays'] = duelist['AgeingDays'].fillna("")
duelist.head(2)

,BBB,AT,AcTypeDesc,CC,OldClientCode,ClientCode,OldAcNum,MainCode,Name,Address,...,ModelDetails,LotNumber,DownPayment,VehicleModel,VehicleNo,Region,Obligor,DistrictCode,IntRateOfChgAc,ExpiryDateOfChgAc
18993,001,32,HP - HEAVY EQUIPMENT,01,NaN,00005629,NaN,00103200005629000002,AAYON NIRMAN SEWA PVT.LTD,"GHORAHI-10,DANG GHORAHI-10,DANG",...,JCB JS 220 TRACKED EXCAVATOR,NaN,40% Downpayment,7 HEAVY MACHINE,NaN,MID WESTERN,NaN,053,0.0,03/07/2025
19356,001,32,HP - HEAVY EQUIPMENT,01,001817,00003833,82001817041,00103200003833000004,RIDIPA CONSTRUCTION,Tewang-8 rolpa Rolpa District RAPTI ZONE,...,JCB JS205 LC Tracked Excavator,NaN,25% Downpayment,NaN,Ra 1 Ka 465,MID-WESTERN REGION,NaN,053,0.0,21/03/2025

In [ ]:
pos = duelist.columns.get_loc("Name") + 1
duelist.insert(pos, "Ageing", "")
duelist.insert(pos, "Loan Type", "")
duelist.insert(pos, "OfficerName", "")

pos = duelist.columns.get_loc("TotCharge") + 1
duelist.insert(pos, "OvDueWithInsurance","")
duelist.insert(pos, "InsurancePremium", "")
duelist.insert(pos, "TotOvDue", "")

pos = duelist.columns.get_loc("AgeingDays") + 1
duelist.insert(pos, "Bucket", "")

pos = duelist.columns.get_loc("BranchName") + 1
duelist.insert(pos, "Dealer Name", "")

In [51]:
duelist.to_excel(output_file, index = False)